name: Update EPG
on:
  schedule:
    - cron: "0 2 * * *" # Exécute à 2h du matin tous les jours 
  workflow_dispatch: # Permet l'exécution manuelle 

jobs:
  Update-EPG:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v4
        
      - name: checkout iptv-org/epg repo
        uses: actions/checkout@v4
        with:
         repository: iptv-org/epg
         path: iptv-org-epg

      - name: update EPG
        run: sh EPG/epg.sh

      - name: setup git config
        run: |
          git config user.name "Rodri Robot EPG"
          git config user.email "<>"

      - name: commit
        run: |
          git push https://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:${TOKEN_ACCES_REPO}@github.com/Rodri-06009/Rodri-06009.github.io.git
          git pull
          cd EPG && git add .
          git commit -m "Update EPG"
          git push origin main

      - name: Convert EPG
        run: sh EPG/epg-convert.sh

      - name: setup git config
        run: |
          git config user.name "Rodri Robot EPG"
          git config user.email "<>"

      - name: commit
        run: |
          git push https://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:${TOKEN_ACCES_REPO}@github.com/Rodri-06009/Rodri-06009.github.io.git
          git pull
          cd EPG && git add .
          git commit -m "Convert EPG"
          git push origin main

      - name: Delete epg-rodri.xml
        run: sh EPG/EPG-Delete-XML.sh

      - name: setup git config
        run: |
          git config user.name "Rodri Robot EPG"
          git config user.email "<>"

      - name: commit
        run: |
          git push https://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:${TOKEN_ACCES_REPO}@github.com/Rodri-06009/Rodri-06009.github.io.git
          git pull
          cd EPG && git add .
          git commit -m "epg-rodri.xml delete"
          git push origin main
