name: Update EPG

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  Update-EPG:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run EPG update script
        run: bash EPG/epg.sh  # Assurez-vous que le chemin est correct

      - name: Setup Git config
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Commit changes
        run: |
          git pull
          cd EPG
          git add .
          git commit -m "Update EPG" || echo "No changes to commit"
          git push origin main  # Ajustez si nécessaire
